url: 
baseurl: 

# Site settings
title: Beans Studio
email: 
description: "Leading mobile application development companies"


# Team names, titles and social links
people:
- name: Hong Dam
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: behance-square
      url: https://www.behance.net/hongdt212
    - title: linkedin
      url: https://www.linkedin.com/in/dam-hong-622a48110

- name: Tao Pham
  pic: 2
  position: Lead Android
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/tao-pham-duy-560363a0/
    - title: github
      url: https://github.com/Taopd

- name: Trung Nguyen
  pic: 3
  position: Lead iOS
  social:
    - title: twitter
      url: https://twitter.com/geek1706
    - title: stack-overflow
      url: https://stackoverflow.com/cv/geek1706
    - title: github
      url: https://twitter.com/geek1706

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty